imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }


# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig','php']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '/var/lib/php/sessions'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


# KNP paginator
knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template


easy_admin:
    site_name: 'Project Initiation Documents Dashboard'
    design:
        brand_color: '#0064AA'
        menu:
            - 'Pid'
            - 'Financial'
            - 'User'
            - { label: 'Your front end', route: 'list_user_pids' }
            - { label: 'Master gantt chart', route: 'gantt_master_pids' }


    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

    list:
        title: 'List of %%entity_label%%'

    entities:
        Pid:
            class: AppBundle\Entity\Pid
            disabled_actions: ['new']
            list:
                actions:
                    - { name: 'edit', icon: 'pencil',label: '', title: 'edit'  }
                    - { name: 'delete', icon: 'trash',label: '', title: 'delete' }


                fields:
                    - 'id'
                    - 'title'
                    - 'owner'
                    - 'description'
                    - 'RAG'
                    - { property: 'approved', type: 'text'}
                    - { property: 'pidstart', type: 'date', format: 'd M Y'  }
                    - { property: 'pidend', type: 'date', format: 'd M Y'  }


            form:
                title: 'Project Initiation Document'

                fields:

                    - 'id'
                    - 'title'
                    - 'description'
                    -
                        property: 'rag'
                        type: 'choice'
                        type_options:
                            choices: {'RED': 'RED','AMBER': 'AMBER','GREEN': 'GREEN'}
                    -
                        property: 'approval'
                        type: 'choice'
                        type_options:
                            choices: {'yes': 'yes','no': 'no'}
                    - 'budgetrequested'
                    - 'budgetspent'
                    - 'budgetallocated'
                    - 'remainingamount'
                    - 'assets'
                    - { property: 'owner', type: 'entity' }
                    -
                        property: 'alsoinvolved'
                        type: 'entity'
                        type_options:
                            class: 'AppBundle\Entity\User'
                            multiple: false
                            label: 'Also involved'
                    -
                        property: 'tasks'
                        type: 'collection'
                        type_options:
                            entry_type: AppBundle\Form\TaskEmbeddedForm
                            allow_delete: true
                            allow_add: true
                            by_reference: false


        Financial:
            class: AppBundle\Entity\Pid
            disabled_actions: ['new','edit','delete']

            list:
                fields:
                    - 'id'
                    - 'title'
                    - 'description'
                    - 'RAG'
                    - 'approval'
                    - 'budgetrequested'
                    - 'budgetspent'
                    - 'budgetallocated'
                    - 'remainingamount'

        User:
            class: AppBundle\Entity\User

            form:
                fields:
                    - 'id'
                    - 'username'
                    - 'name'
                    - 'email'
                    -
                        property: 'roles'
                        type: 'choice'
                        label: 'Roles'
                        type_options:
                            multiple: true
                            choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_SUPERADMIN': 'ROLE_SUPERADMIN' }
                    -
                        property: 'linemanager'
                        type: 'entity'
                        type_options:
                            class: 'AppBundle\Entity\User'
                            multiple: false
                            label: 'Line Manager'
                    - { property: 'plainpassword', type: 'text'}

            new:
                fields:
                    - '-id'
                    - 'username'
                    - 'name'
                    - 'email'
                    - 'roles'
                    - 'linemanager'
                    - { property: 'plainpassword', type: 'text' }
